rm(list = ls())
gc(verbose = TRUE,reset = TRUE)
source("HSHS_DataSet1.R")
rm(list = ls())
gc(verbose = TRUE,reset = TRUE)
source("HSHS_DataSet2.R")
rm(list = ls())
gc(verbose = TRUE,reset = TRUE)
source("HSHS_DataSet3.R")
rm(list = ls())
gc(verbose = TRUE,reset = TRUE)
source("HSHS_DataSet4.R")
